### ISSUE TITLE
Which Source Engine version does CSO2 use?

### ISSUE THREAD

**Issue by felixabi** [L-Leite/cso2-launcher#75]
Which engine version does cso2 use? | Source 2006 2007 2009?

**Comment by L-Leite** [comment]
It's a custom engine, but I would say it's closer to Source Engine 2013. [CSO Wiki](https://cso.fandom.com/wiki/Counter-Strike_Online_2) says that the CSO2 close beta test in "August 2, 2012".

I didn't search far for evidence, but:
- The net protocol is the same as the latest Steam Counter-Strike: Source build (version 24);
- Both CSS and CSO2 export the interface `VEngineServer021`, but only CSS has `VEngineServer022` and `VEngineServer023`.

Either way some of engine structures were modified by Nexon, such as the map file lumps, in order to support maps like Big City I believe.

**Comment by felixabi** [comment]
ty
